# Generated by Django 5.2.1 on 2025-05-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_comment_options_remove_comment_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'comentário', 'verbose_name_plural': 'comentários'},
        ),
        migrations.AddField(
            model_name='comment',
            name='captcha_token',
            field=models.CharField(blank=True, help_text='Token de verificação do captcha', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Endereço IP do autor do comentário', null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_agent',
            field=models.TextField(blank=True, help_text='User-Agent do navegador do autor', null=True),
        ),
    ]
