# Generated by Django 5.2.1 on 2025-05-17 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0007_auto_20250515_1536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
