# Generated by Django 5.2.1 on 2025-05-17 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_views_count_alter_bookcomment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookComment',
        ),
    ]
